# Generated by Django 5.1.15 on 2026-05-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacaciones', '0002_add_missing_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solicitudpermiso',
            name='solicpermiso_fechas_idx',
        ),
        migrations.RemoveIndex(
            model_name='ventavacaciones',
            name='ventavac_personal_idx',
        ),
    ]
