# Generated by Django 5.1.15 on 2026-05-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaprestamo',
            name='descuento_planilla',
            field=models.ForeignKey(blank=True, help_text='Si se descontó en una planilla específica (DescuentoPlanilla)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuotas_prestamo', to='descuentos.descuentoplanilla'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_desembolso',
            field=models.DateField(blank=True, help_text='Fecha en la que se entregó el dinero al trabajador', null=True, verbose_name='Fecha de Desembolso'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Si fue rechazado, motivo dado por el aprobador', verbose_name='Motivo del Rechazo'),
        ),
        migrations.AlterField(
            model_name='cuotaprestamo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('DESCONTADA', 'Descontada en planilla'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago Parcial'), ('VENCIDA', 'Vencida'), ('CONDONADO', 'Condonado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente Aprobación'), ('APROBADO', 'Aprobado'), ('EN_CURSO', 'Desembolsado / En Curso'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=12),
        ),
    ]
