# Generated by Django 5.1.15 on 2026-03-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_knowledge_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgearticle',
            name='embedding_json',
            field=models.TextField(blank=True, help_text='Vector de embedding en JSON (float[1536]). Auto-generado por: python manage.py index_knowledge_embeddings', null=True),
        ),
    ]
