# Generated by Django 5.1.15 on 2026-05-25 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_knowledge_article_pgvector'),
        ('empresas', '0010_empresa_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, help_text='Nombre del modelo: Personal, SolicitudVacacion, Prestamo, etc.', max_length=80)),
                ('entity_id', models.BigIntegerField(db_index=True, help_text='PK del objeto modificado (puede no existir si fue DELETE).')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación')], db_index=True, max_length=10)),
                ('cambios', models.JSONField(blank=True, default=dict, help_text='Diff por campo: {campo: {"old": valor_ant, "new": valor_nuevo}}.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Contexto: request_ip, user_agent, source (web/celery/admin), etc.')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Auditoría',
                'verbose_name_plural': 'Entradas de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-fecha'], name='audit_entry_entity_fecha_idx'), models.Index(fields=['usuario', '-fecha'], name='audit_entry_usuario_fecha_idx'), models.Index(fields=['-fecha'], name='audit_entry_fecha_idx')],
            },
        ),
    ]
