# Generated by Django 5.1.15 on 2026-07-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciausuario',
            name='landing_default',
            field=models.CharField(choices=[('home', 'Dashboard general'), ('aprobaciones', 'Centro de Aprobaciones'), ('mi_dia_reclutador', 'Mi Día — Reclutamiento'), ('mi_dia_nominas', 'Mi Día — Nóminas')], default='home', help_text='A dónde llegas al entrar al sistema.', max_length=20, verbose_name='Pantalla de inicio'),
        ),
    ]
