# Generated by Django 5.1.15 on 2026-05-20 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_boletapago_tracking_lectura'),
        ('personal', '0033_personal_personal_empresa_estado_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActividadTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('LOGIN_FAILED', 'Intento fallido de login'), ('VIEW_BOLETA', 'Visualización de boleta'), ('DOWNLOAD_BOLETA', 'Descarga de boleta PDF'), ('CONFIRM_BOLETA', 'Confirmación de recepción de boleta'), ('VIEW_BANCO_HORAS', 'Vista del banco de horas'), ('VIEW_VACACIONES', 'Vista de saldo de vacaciones'), ('CHANGE_PASSWORD', 'Cambio de contraseña'), ('UPDATE_PROFILE', 'Actualización de perfil'), ('OTRO', 'Otro evento')], db_index=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('objeto_id', models.CharField(blank=True, default='', max_length=50)),
                ('objeto_tipo', models.CharField(blank=True, default='', help_text='Modelo del objeto referenciado (ej: BoletaPago, RegistroNomina).', max_length=30)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_log', to='personal.personal', verbose_name='Trabajador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de actividad',
                'verbose_name_plural': 'Logs de actividad',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['personal', '-timestamp'], name='documentos__persona_11c1db_idx'), models.Index(fields=['personal', 'tipo', '-timestamp'], name='documentos__persona_154083_idx'), models.Index(fields=['tipo', '-timestamp'], name='documentos__tipo_2ff773_idx')],
            },
        ),
    ]
