# Generated by Django 5.1.15 on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_consentimiento_acuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='vigencia_dias',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Si tiene vencimiento, días de vigencia desde la fecha de emisión '
                          '(usado para auto-calcular fecha_vencimiento al subir).',
                null=True,
            ),
        ),
    ]
