# Generated by Django 5.1.15 on 2026-05-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0013_add_tipodocumento_vigencia_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acusereciboboleta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consentimientoboletaelectronica',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
