# Generated by Django 5.1.15 on 2026-05-29 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descargo',
            name='archivos_adjuntos',
            field=models.FileField(blank=True, null=True, upload_to='disciplinaria/descargos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Adjuntos'),
        ),
        migrations.AlterField(
            model_name='medidadisciplinaria',
            name='documento_preaviso',
            field=models.FileField(blank=True, null=True, upload_to='disciplinaria/cartas/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Carta de Preaviso'),
        ),
        migrations.AlterField(
            model_name='medidadisciplinaria',
            name='documento_resolucion',
            field=models.FileField(blank=True, null=True, upload_to='disciplinaria/resoluciones/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Documento Resolución'),
        ),
        migrations.AlterField(
            model_name='medidadisciplinaria',
            name='evidencias',
            field=models.FileField(blank=True, null=True, upload_to='disciplinaria/evidencias/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'mp4', 'mp3'])], verbose_name='Evidencias'),
        ),
    ]
