# Generated by Django 5.1.15 on 2026-05-22 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_objetivoclave_resultadoclave_checkinokr_and_more'),
        ('personal', '0033_personal_personal_empresa_estado_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej: 2026-Q2, 2026-Anual', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_CURSO', 'En curso'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=12)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personal_evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_360', to='personal.personal', verbose_name='Evaluado')),
            ],
            options={
                'verbose_name': 'Evaluación 360°',
                'verbose_name_plural': 'Evaluaciones 360°',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteEvaluacion360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTOEVALUACION', 'Autoevaluación'), ('MANAGER', 'Manager'), ('PEER', 'Par / Colega'), ('SUBORDINADO', 'Subordinado'), ('CLIENTE_INTERNO', 'Cliente interno')], max_length=20)),
                ('completada', models.BooleanField(default=False)),
                ('puntaje_global', models.DecimalField(blank=True, decimal_places=2, help_text='Promedio 0-5', max_digits=4, null=True)),
                ('comentario_general', models.TextField(blank=True)),
                ('fortalezas', models.TextField(blank=True)),
                ('areas_mejora', models.TextField(blank=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='evaluaciones.evaluacion360')),
                ('personal_evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones_360', to='personal.personal', verbose_name='Evaluador')),
            ],
            options={
                'verbose_name': 'Participante 360°',
                'verbose_name_plural': 'Participantes 360°',
                'ordering': ['tipo', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCompetencia360',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_codigo', models.SlugField(max_length=40)),
                ('competencia_label', models.CharField(max_length=120)),
                ('puntaje', models.DecimalField(decimal_places=1, help_text='Escala 0-5', max_digits=3)),
                ('comentario', models.TextField(blank=True)),
                ('competencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='evaluaciones.competencia')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluaciones.participanteevaluacion360')),
            ],
            options={
                'verbose_name': 'Respuesta 360°',
                'verbose_name_plural': 'Respuestas 360°',
                'ordering': ['competencia_codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluacion360',
            index=models.Index(fields=['estado', 'periodo'], name='evaluacione_estado_ca4043_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion360',
            index=models.Index(fields=['personal_evaluado', 'periodo'], name='evaluacione_persona_1ea9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='participanteevaluacion360',
            index=models.Index(fields=['evaluacion', 'tipo'], name='evaluacione_evaluac_d2ea8e_idx'),
        ),
        migrations.AddIndex(
            model_name='participanteevaluacion360',
            index=models.Index(fields=['personal_evaluador', 'completada'], name='evaluacione_persona_890fea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestacompetencia360',
            unique_together={('participante', 'competencia_codigo')},
        ),
    ]
