# Generated by Django 5.1.15 on 2026-03-05 02:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('nominas', '0002_add_empresa_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.SmallIntegerField(verbose_name='Año')),
                ('mes', models.SmallIntegerField(help_text='1-12', verbose_name='Mes')),
                ('presup_rem_bruta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Rem. Bruta presupuestada')),
                ('presup_cond_trabajo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Cond. Trabajo/Hospedaje (presup.)')),
                ('presup_alimentacion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Alimentación (presup.)')),
                ('presup_essalud', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='EsSalud/PLAME (presup.)')),
                ('presup_gratif', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Gratificaciones provisión (presup.)')),
                ('presup_cts', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='CTS provisión (presup.)')),
                ('presup_liquidaciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Liquidaciones (presup.)')),
                ('presup_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total desembolso presupuestado')),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_planilla', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Presupuesto de Planilla',
                'verbose_name_plural': 'Presupuestos de Planilla',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes', 'empresa')},
            },
        ),
    ]
