# Generated by Django 5.1.15 on 2026-05-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0011_registronomina_hash_integridad'),
        ('personal', '0032_merge_0029_activoasignado_0031_merge_20260413_2247'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lineanomina',
            index=models.Index(fields=['registro', 'concepto'], name='linom_reg_concepto_idx'),
        ),
        migrations.AddIndex(
            model_name='registronomina',
            index=models.Index(fields=['periodo', 'estado'], name='regnom_periodo_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='registronomina',
            index=models.Index(fields=['personal', '-periodo'], name='regnom_personal_periodo_idx'),
        ),
    ]
