# Generated by Django 5.1.15 on 2026-05-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0012_lineanomina_linom_reg_concepto_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodonomina',
            name='contabilizado',
            field=models.BooleanField(default=False, help_text='Marcado al exportar el asiento a CONCAR/Siscont/SAP/SIRE.', verbose_name='Contabilizado'),
        ),
        migrations.AddField(
            model_name='periodonomina',
            name='contabilizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodonomina',
            name='contabilizado_formato',
            field=models.CharField(blank=True, help_text='Formato usado: CONCAR, SISCONT, SAP_EXCEL, SIRE_PLE, SIGO.', max_length=20),
        ),
    ]
