# Generated by Django 5.1.15 on 2026-05-21 16:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_empresa_plan_cuentas'),
        ('nominas', '0013_periodonomina_contabilizado_and_more'),
        ('personal', '0033_personal_personal_empresa_estado_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionApertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('total_trabajadores', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(blank=True, help_text='Vacío = configuración global (multi-empresa).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_apertura', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Apertura',
                'verbose_name_plural': 'Configuraciones de Apertura',
            },
        ),
        migrations.CreateModel(
            name='SaldoAperturaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_corte', models.DateField(help_text='Fecha hasta la cual el sistema anterior procesó planilla. Desde el día siguiente, Harmoni asume el cálculo.', verbose_name='Fecha de corte')),
                ('prov_cts', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Provisión CTS acumulada')),
                ('prov_gratificacion', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Provisión Gratificación')),
                ('prov_vacaciones', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Provisión Vacaciones')),
                ('dias_vacaciones_pendientes', models.IntegerField(default=0, verbose_name='Días vacaciones pendientes')),
                ('ir5_acumulado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='IR 5ta acumulado del año')),
                ('prestamo_saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Saldo préstamo vigente')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_apertura', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Saldo de Apertura',
                'verbose_name_plural': 'Saldos de Apertura',
                'ordering': ['personal__apellidos_nombres'],
            },
        ),
    ]
