# Generated by Django 5.1.15 on 2026-05-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_empresa_plan'),
        ('nominas', '0016_concepto_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoauditlog',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa del contexto en que se hizo el cambio. Null = global/sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='empresas.empresa'),
        ),
    ]
