# Generated by Django 5.1.15 on 2026-05-24 05:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_empresa_plan'),
        ('nominas', '0017_conceptoauditlog_empresa'),
        ('personal', '0034_add_roster_gastro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAgenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text='Título auto-generado a partir del primer mensaje', max_length=200)),
                ('contexto', models.JSONField(blank=True, default=dict, help_text='Contexto persistente: trabajador en foco, período, etc.')),
                ('creada_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('archivada', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='empresas.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_nominas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación Agente IA',
                'verbose_name_plural': 'Conversaciones Agente IA',
                'ordering': ['-actualizada_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAgenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente IA'), ('tool', 'Tool (resultado de función)'), ('system', 'Sistema (instrucciones)')], max_length=15)),
                ('contenido', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=80)),
                ('tool_args', models.JSONField(blank=True, default=dict)),
                ('tool_result', models.JSONField(blank=True, default=dict)),
                ('tokens_input', models.PositiveIntegerField(default=0)),
                ('tokens_output', models.PositiveIntegerField(default=0)),
                ('modelo', models.CharField(blank=True, help_text='ej: deepseek-chat, gemini-1.5-pro, gpt-4o-mini', max_length=80)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('requiere_aprobacion', models.BooleanField(default=False)),
                ('accion_propuesta', models.JSONField(blank=True, default=dict)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='nominas.conversacionagenteia')),
            ],
            options={
                'verbose_name': 'Mensaje Agente IA',
                'verbose_name_plural': 'Mensajes Agente IA',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditAgenteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CONSULTA_NORMATIVA', 'Consulta a normativa (RAG)'), ('OBTENER_BOLETA', 'Lectura de boleta histórica'), ('CALCULO_REINTEGRO', 'Cálculo de reintegro'), ('SIMULAR_IMPACTO', 'Simulación de impacto'), ('PROPONER_REINTEGRO', 'Propuesta de reintegro (estado PROPUESTO)'), ('APLICAR_REINTEGRO', 'Aplicación de reintegro (genera LineaNomina)'), ('REVERTIR_REINTEGRO', 'Reversión de reintegro'), ('CONVERSACION', 'Mensaje conversacional (sin tool)'), ('ERROR', 'Error / rechazo')], max_length=30)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('exito', models.BooleanField(default=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='nominas.conversacionagenteia')),
            ],
            options={
                'verbose_name': 'Audit Agente IA',
                'verbose_name_plural': 'Audit Agente IA',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='nominas_aud_fecha_575de4_idx'), models.Index(fields=['accion', '-fecha'], name='nominas_aud_accion_aac99b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReintegroNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('ERROR_SUELDO', 'Error en sueldo base'), ('AUMENTO_RETROACTIVO', 'Aumento de sueldo retroactivo'), ('HE_NO_PAGADAS', 'Horas extra no pagadas'), ('ASIG_FAMILIAR_OMITIDA', 'Asignación familiar omitida'), ('BONIF_OMITIDA', 'Bonificación omitida'), ('GRATIF_MAL_CALCULADA', 'Gratificación mal calculada'), ('SENTENCIA_JUDICIAL', 'Sentencia judicial'), ('OTRO', 'Otro (especificar)')], max_length=30)),
                ('descripcion', models.TextField(help_text='Justificación clara — irá en la boleta como detalle')),
                ('periodo_origen_anio', models.SmallIntegerField(help_text='Año del período donde ocurrió el error')),
                ('periodo_origen_mes', models.SmallIntegerField(help_text='Mes del período donde ocurrió el error')),
                ('monto_que_se_pago', models.DecimalField(decimal_places=2, help_text='Lo que el trabajador efectivamente recibió', max_digits=14)),
                ('monto_correcto', models.DecimalField(decimal_places=2, help_text='Lo que debió haber recibido según corrección', max_digits=14)),
                ('monto_reintegro', models.DecimalField(decimal_places=2, help_text='Diferencia a pagar (positiva) o a descontar (negativa)', max_digits=14)),
                ('impacto_ir_5ta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('impacto_aportes', models.JSONField(blank=True, default=dict, help_text='ej: {"AFP_aporte": 50.00, "ESSALUD_emp": 27.00, ...}')),
                ('monto_neto_reintegro', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Líquido después de descontar aportes adicionales', max_digits=14)),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('APROBADO', 'Aprobado'), ('APLICADO', 'Aplicado'), ('REVERSADO', 'Reversado')], default='PROPUESTO', max_length=12)),
                ('propuesto_por_ia', models.BooleanField(default=False, help_text='True si fue propuesto por el agente IA (vs admin manual)')),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('revertido_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_reversion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegros_aprobados', to=settings.AUTH_USER_MODEL)),
                ('conversacion_ia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegros_propuestos', to='nominas.conversacionagenteia')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='empresas.empresa')),
                ('linea_generada', models.ForeignKey(blank=True, help_text='Línea creada al aplicar el reintegro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nominas.lineanomina')),
                ('periodo_aplicar', models.ForeignKey(blank=True, help_text='Período donde se generará la línea de reintegro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegros_aplicados', to='nominas.periodonomina')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reintegros', to='personal.personal')),
                ('propuesto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegros_propuestos', to=settings.AUTH_USER_MODEL)),
                ('revertido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintegros_revertidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reintegro de Nómina',
                'verbose_name_plural': 'Reintegros de Nómina',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['personal', '-creado_en'], name='nominas_rei_persona_ccc85c_idx'), models.Index(fields=['estado', '-creado_en'], name='nominas_rei_estado_45f2a2_idx')],
            },
        ),
    ]
