# Generated by Django 5.1.15 on 2026-05-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0007_recargaalimentacion'),
        ('nominas', '0018_conversacionagenteia_mensajeagenteia_auditagenteia_and_more'),
    ]

    operations = [
    ]
