# Generated by Django 5.1.15 on 2026-05-25 01:57
# Reconcilia leaf nodes en producción tras aplicar 0019_merge.
# Dependencies corregidas: apunta a las versiones canónicas del repo.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0007_recargaalimentacion'),
        ('nominas', '0019_merge_20260524_1258'),
    ]

    operations = [
    ]
