# Generated by Django 5.1.15 on 2026-05-25 05:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0020_merge_20260524_2057'),
        ('personal', '0036_merge_20260524_2057'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cese', models.DateField(verbose_name='Fecha de cese')),
                ('motivo_cese', models.CharField(choices=[('RENUNCIA', 'Renuncia voluntaria'), ('DESPIDO', 'Despido (causa justa)'), ('DESPIDO_ARB', 'Despido arbitrario (indemnización)'), ('MUTUO', 'Mutuo disenso'), ('CADUCIDAD', 'Caducidad de contrato'), ('JUBILACION', 'Jubilación'), ('FALLECIMIENTO', 'Fallecimiento'), ('PERIODO_PRUEBA', 'No supera período de prueba')], default='RENUNCIA', max_length=20, verbose_name='Motivo del cese')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('vacaciones_truncas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Vacaciones truncas')),
                ('gratif_trunca', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Gratificación trunca')),
                ('cts_trunca', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='CTS trunca')),
                ('sueldo_mes_curso', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Sueldo del mes en curso')),
                ('he_no_compensadas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Horas extra no compensadas')),
                ('indemnizacion', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='1.5 sueldos × año (máx 12 sueldos) — solo motivo DESPIDO_ARB. Art. 38 DS 003-97-TR.', max_digits=12, verbose_name='Indemnización por despido arbitrario')),
                ('otros_pagos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Otros pagos')),
                ('prestamos_pendientes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Préstamos pendientes')),
                ('adelantos_pendientes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Adelantos pendientes')),
                ('embargo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Embargo judicial')),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Otros descuentos')),
                ('total_bruto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total bruto (haberes)')),
                ('total_neto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total neto (bruto − descuentos)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADA', 'Calculada'), ('APROBADA', 'Aprobada por RRHH'), ('FIRMADA', 'Firmada por trabajador'), ('PAGADA', 'Pagada'), ('CERRADA', 'Cerrada')], db_index=True, default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('firmada_en', models.DateTimeField(blank=True, null=True, verbose_name='Firmada el')),
                ('pagada_en', models.DateTimeField(blank=True, null=True, verbose_name='Pagada el')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobada por')),
                ('instancia_flujo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacion_origen', to='workflows.instanciaflujo', verbose_name='Instancia de flujo offboarding')),
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacion', to='personal.personal', verbose_name='Trabajador cesado')),
                ('registro_nomina', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacion_origen', to='nominas.registronomina', verbose_name='Registro de nómina (boleta unificada)')),
            ],
            options={
                'verbose_name': 'Liquidación Laboral',
                'verbose_name_plural': 'Liquidaciones Laborales',
                'ordering': ['-fecha_cese', '-creado_en'],
                'indexes': [models.Index(fields=['estado', '-fecha_cese'], name='nominas_liq_estado_556b60_idx'), models.Index(fields=['motivo_cese', '-fecha_cese'], name='nominas_liq_motivo__0abd09_idx')],
            },
        ),
    ]
