# Generated by Django 5.1.15 on 2026-05-25 05:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_empresa_plan'),
        ('nominas', '0021_liquidacionlaboral'),
        ('personal', '0036_merge_20260524_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPropinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('POOL_PUNTOS', 'Pool por puntos (recomendado)'), ('POOL_PAREJO', 'Pool dividido parejo'), ('INDIVIDUAL', 'Individual (no se aplica pool)')], default='POOL_PUNTOS', help_text='POOL_PUNTOS: reparto proporcional a puntos por cargo. POOL_PAREJO: monto total dividido entre N participantes. INDIVIDUAL: no se reparte vía pool.', max_length=20)),
                ('incluye_cocina', models.BooleanField(default=True, help_text='Si se incluye al personal de cocina en el reparto.')),
                ('incluye_admin', models.BooleanField(default=False, help_text='Si se incluye al personal administrativo en el reparto.')),
                ('porcentaje_casa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='% que retiene el local del monto bruto (rotura, reposición, gastos). Ej: 5 = 5%.', max_digits=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_propinas', to='empresas.empresa', verbose_name='Empresa / Local')),
            ],
            options={
                'verbose_name': 'Configuración de Propinas',
                'verbose_name_plural': 'Configuraciones de Propinas',
            },
        ),
        migrations.CreateModel(
            name='PoolPropinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_bruto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto total recolectado en el período (antes de % casa).', max_digits=12)),
                ('distribuido', models.BooleanField(default=False)),
                ('distribuido_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools_propinas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Pool de Propinas',
                'verbose_name_plural': 'Pools de Propinas',
                'ordering': ['-fecha_fin', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='DistribucionPropinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en_nomina', models.ForeignKey(blank=True, help_text='RegistroNomina donde se imputó este monto (trazabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propinas_aplicadas', to='nominas.registronomina')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propinas_recibidas', to='personal.personal')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribuciones', to='nominas.poolpropinas')),
            ],
            options={
                'verbose_name': 'Distribución de Propinas',
                'verbose_name_plural': 'Distribuciones de Propinas',
                'ordering': ['pool', '-monto'],
            },
        ),
        migrations.CreateModel(
            name='PuntosPropinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Puntos del cargo. Ej: Mozo=3, Bartender=2.5, Cocina=1.', max_digits=4)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_propinas', to='personal.cargo')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_por_cargo', to='nominas.configuracionpropinas')),
            ],
            options={
                'verbose_name': 'Puntos por Cargo',
                'verbose_name_plural': 'Puntos por Cargo',
                'ordering': ['-puntos', 'cargo__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='poolpropinas',
            index=models.Index(fields=['empresa', '-fecha_fin'], name='nominas_poo_empresa_d3585c_idx'),
        ),
        migrations.AddIndex(
            model_name='poolpropinas',
            index=models.Index(fields=['distribuido'], name='nominas_poo_distrib_bf798a_idx'),
        ),
        migrations.AddIndex(
            model_name='distribucionpropinas',
            index=models.Index(fields=['pool', '-monto'], name='nominas_dis_pool_id_43f1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='distribucionpropinas',
            index=models.Index(fields=['personal', '-creado_en'], name='nominas_dis_persona_c8d4aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='puntospropinas',
            unique_together={('configuracion', 'cargo')},
        ),
    ]
