# Generated by Django 5.1.15 on 2026-05-25 06:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0022_propinas_pool'),
        ('personal', '0036_merge_20260524_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasTrabajadasPropinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Horas trabajadas en el período del pool. Ej: 42.50.', max_digits=6)),
            ],
            options={
                'verbose_name': 'Horas trabajadas (Pool Propinas)',
                'verbose_name_plural': 'Horas trabajadas (Pool Propinas)',
            },
        ),
        migrations.AddField(
            model_name='configuracionpropinas',
            name='porcentaje_tipout_boh',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='% del distribuible que se separa para BOH (cocina) ANTES del reparto al FOH. Ej: 15 = 15%. Práctica US estándar 70/15/10/5. Si incluye_cocina=True este % es ignorado (la cocina ya entra al pool principal).', max_digits=5),
        ),
        migrations.AddField(
            model_name='distribucionpropinas',
            name='anomalia',
            field=models.BooleanField(default=False, help_text='True si el monto recibido es < 50% del promedio del cargo. Útil para revisar manualmente antes de pagar (best practice TipHaus / Toast).'),
        ),
        migrations.AddField(
            model_name='distribucionpropinas',
            name='es_tipout_boh',
            field=models.BooleanField(default=False, help_text='True si la distribución corresponde al tip-out hacia BOH (cocina), separado del pool principal.'),
        ),
        migrations.AddField(
            model_name='distribucionpropinas',
            name='horas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Horas usadas en el cálculo (modos *_HORAS).', max_digits=6),
        ),
        migrations.AddField(
            model_name='poolpropinas',
            name='monto_card',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Propinas vía tarjeta (capturadas por POS) en el período.', max_digits=12),
        ),
        migrations.AddField(
            model_name='poolpropinas',
            name='monto_cash',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Propinas en efectivo declaradas en el período.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='configuracionpropinas',
            name='incluye_cocina',
            field=models.BooleanField(default=True, help_text='Si se incluye al personal de cocina en el reparto (BOH).'),
        ),
        migrations.AlterField(
            model_name='configuracionpropinas',
            name='modo',
            field=models.CharField(choices=[('POOL_PUNTOS', 'Pool por puntos (cargo/jerarquía)'), ('POOL_PAREJO', 'Pool dividido parejo'), ('POOL_HORAS', 'Pool por horas trabajadas'), ('POOL_PUNTOS_HORAS', 'Pool por puntos × horas (recomendado)'), ('INDIVIDUAL', 'Individual (no se aplica pool)')], default='POOL_PUNTOS', help_text='POOL_PUNTOS_HORAS es la práctica mundial estándar (7shifts/Toast).', max_length=20),
        ),
        migrations.AlterField(
            model_name='poolpropinas',
            name='monto_bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto total bruto = cash + card. Se recalcula en save() si cash o card están seteados; legacy para retro-compat.', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='distribucionpropinas',
            index=models.Index(fields=['anomalia'], name='nominas_dis_anomali_1bb647_idx'),
        ),
        migrations.AddField(
            model_name='horastrabajadaspropinas',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_pool_propinas', to='personal.personal'),
        ),
        migrations.AddField(
            model_name='horastrabajadaspropinas',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='nominas.poolpropinas'),
        ),
        migrations.AddIndex(
            model_name='horastrabajadaspropinas',
            index=models.Index(fields=['pool', 'personal'], name='nominas_hor_pool_id_0bad39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horastrabajadaspropinas',
            unique_together={('pool', 'personal')},
        ),
    ]
