# Generated by Django 5.1.15 on 2026-05-30 08:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0024_registronomina_conceptos_manuales'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidacionlaboral',
            name='descuento_pension',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aporte pensionario sobre los conceptos afectos (sueldo del mes + gratif. trunca). CTS y vacaciones son inafectas.', max_digits=12, verbose_name='Descuento AFP/ONP'),
        ),
    ]
