# Generated by Django 5.1.15 on 2026-06-03 05:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0025_liquidacionlaboral_descuento_pension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionlaboral',
            name='descuento_pension',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Aporte pensionario sobre la remuneración afecta (sueldo del mes en curso). Gratificación trunca, CTS y vacaciones son inafectas (Ley 29351 / Ley 30334).', max_digits=12, verbose_name='Descuento AFP/ONP'),
        ),
    ]
