# Generated by Django 5.1.15 on 2026-06-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0026_alter_liquidacionlaboral_descuento_pension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditagenteia',
            name='accion',
            field=models.CharField(choices=[('CONSULTA_NORMATIVA', 'Consulta a normativa (RAG)'), ('OBTENER_BOLETA', 'Lectura de boleta histórica'), ('CALCULO_REINTEGRO', 'Cálculo de reintegro'), ('SIMULAR_IMPACTO', 'Simulación de impacto'), ('PROPONER_REINTEGRO', 'Propuesta de reintegro (estado PROPUESTO)'), ('APLICAR_REINTEGRO', 'Aplicación de reintegro (genera LineaNomina)'), ('REVERTIR_REINTEGRO', 'Reversión de reintegro'), ('CONVERSACION', 'Mensaje conversacional (sin tool)'), ('CONSULTA_PENDIENTES', 'Consolidado de aprobaciones pendientes'), ('ERROR', 'Error / rechazo')], max_length=30),
        ),
    ]
