# Generated by Django 5.1.15 on 2026-06-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0027_alter_auditagenteia_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodonomina',
            name='flags_descartados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='periodonomina',
            name='parametros_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Parámetros legales congelados'),
        ),
    ]
