# Generated by Django 5.1.15 on 2026-06-29 23:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0028_periodonomina_flags_descartados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoremunerativo',
            name='aplicar_automatico',
            field=models.BooleanField(default=False, help_text='Si está activo y la fórmula es Porcentaje o Monto fijo, se calcula para todos los trabajadores sin cargarlo manualmente.', verbose_name='Aplicar automáticamente a todos'),
        ),
        migrations.AddField(
            model_name='registronomina',
            name='aporte_sctr_pension',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='registronomina',
            name='aporte_sctr_salud',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='registronomina',
            name='aporte_vida_ley',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='registronomina',
            name='costo_total_empresa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bruto + EsSalud + SCTR (salud+pensión) + Vida Ley + provisiones (gratif+CTS).', max_digits=10),
        ),
    ]
