# Generated by Django 5.1.15 on 2026-07-01 02:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominas', '0029_conceptoremunerativo_aplicar_automatico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornalConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('OPERARIO', 'Operario'), ('OFICIAL', 'Oficial'), ('PEON', 'Peón')], max_length=10)),
                ('jornal_diario', models.DecimalField(decimal_places=2, help_text='Jornal básico diario (S/).', max_digits=8)),
                ('buc_pct', models.DecimalField(decimal_places=2, help_text='BUC (Bonificación Unificada de Construcción) como % del jornal básico. Ej: 32.', max_digits=5)),
                ('bono_altura_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Bono por altura como % del jornal básico (ej: 8). 0 si no aplica.', max_digits=5)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('fuente', models.CharField(default='CAPECO-FTCCP', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Jornal Construcción Civil',
                'verbose_name_plural': 'Jornales Construcción Civil',
                'ordering': ['-vigencia_desde', 'categoria'],
                'constraints': [models.UniqueConstraint(fields=('categoria', 'vigencia_desde'), name='jornal_cc_unique_cat_vigencia')],
            },
        ),
    ]
