# Generated by Django 5.1.15 on 2026-03-06 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0003_add_log_publicacion_vacante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolizaSCTR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SALUD', 'SCTR Salud (cobertura médica)'), ('PENSION', 'SCTR Pensión (invalidez/sepelio)'), ('AMBOS', 'SCTR Ambos (Salud + Pensión)')], max_length=10, verbose_name='Tipo SCTR')),
                ('numero_poliza', models.CharField(max_length=100, verbose_name='Número de Póliza')),
                ('proveedor', models.CharField(choices=[('RIMAC', 'Rímac Seguros'), ('AXA', 'Axa Colpatria'), ('MAPFRE', 'Mapfre Perú'), ('POSITIVA', 'Positiva Seguros'), ('PACIFICO', 'Pacífico Seguros'), ('LA_POSITIVA', 'La Positiva Vida'), ('OTRO', 'Otro')], max_length=15, verbose_name='Aseguradora')),
                ('proveedor_otro', models.CharField(blank=True, max_length=100, verbose_name='Aseguradora (otro)')),
                ('fecha_inicio', models.DateField(verbose_name='Vigencia Desde')),
                ('fecha_fin', models.DateField(verbose_name='Vigencia Hasta')),
                ('monto_asegurado', models.DecimalField(decimal_places=2, default=0, help_text='Generalmente 4 UIT por trabajador cubierto', max_digits=12, verbose_name='Monto Asegurado (S/)')),
                ('aporte_pct', models.DecimalField(decimal_places=4, default=0, help_text='Porcentaje sobre remuneración computable. Varía por nivel de riesgo (0.66%–3.22%).', max_digits=6, verbose_name='Tasa Aporte Empleador (%)')),
                ('trabajadores_cubiertos', models.PositiveIntegerField(default=0, help_text='Número de empleados incluidos en esta póliza', verbose_name='N° Trabajadores Cubiertos')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada'), ('RENOVACION', 'En Renovación')], default='VIGENTE', max_length=12, verbose_name='Estado')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('renovacion_auto', models.BooleanField(default=False, help_text='Marcar si la póliza se renueva automáticamente al vencimiento', verbose_name='Renovación Automática')),
                ('dias_alerta', models.PositiveSmallIntegerField(default=30, help_text='Cuántos días antes del vencimiento se activa la alerta', verbose_name='Días de Alerta Previos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='integraciones/sctr/', verbose_name='PDF de Póliza')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Póliza SCTR',
                'verbose_name_plural': 'Pólizas SCTR',
                'ordering': ['-fecha_fin', 'tipo'],
                'indexes': [models.Index(fields=['estado', 'fecha_fin'], name='integracion_estado_a05f3f_idx'), models.Index(fields=['tipo'], name='integracion_tipo_09deb4_idx')],
            },
        ),
    ]
