# Generated by Django 5.1.15 on 2026-03-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0004_add_poliza_sctr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpublicacionvacante',
            name='plataforma',
            field=models.CharField(choices=[('COMPUTRABAJO', 'Computrabajo Peru'), ('BUMERAN', 'Bumeran Peru'), ('LINKEDIN', 'LinkedIn Jobs'), ('TELEGRAM', 'Telegram Bot'), ('PORTAL', 'Portal de Empleo Propio')], max_length=15, verbose_name='Plataforma'),
        ),
    ]
