# Generated by Django 5.1.15 on 2026-05-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0007_syncsynkrolog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncsynkrolog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
