# Generated by Django 5.1.15 on 2026-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0018_ia_gemini_ocr_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_endpoint',
            field=models.CharField(blank=True, default='http://localhost:11434', help_text='URL del servidor. Ollama: http://localhost:11434 | DeepSeek: https://api.deepseek.com/v1', max_length=200, verbose_name='Endpoint (Ollama / DeepSeek custom)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_modelo',
            field=models.CharField(blank=True, default='gemini-2.5-flash-preview-04-17', help_text='Gemini: gemini-2.5-flash-preview-04-17 | DeepSeek: deepseek-chat | OpenAI: gpt-4o-mini | Ollama: llama3.2', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_ocr_provider',
            field=models.CharField(choices=[('GEMINI', 'Gemini 2.5 Flash (PDF nativos)'), ('NINGUNO', 'Sin OCR IA')], default='NINGUNO', help_text='Gemini Files API para OCR de PDFs escaneados.', max_length=20, verbose_name='Proveedor OCR (PDFs escaneados)'),
        ),
    ]
