# Generated by Django 5.1.15 on 2026-03-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0020_ia_modelo_default_gemini25_stable'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', help_text='Token del bot de Telegram (obtenido desde @BotFather).', max_length=200, verbose_name='Token del Bot de Telegram'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='telegram_channel_id',
            field=models.CharField(blank=True, default='', help_text='@username para canales públicos o -100XXXXXXX para privados.', max_length=100, verbose_name='ID / Username del Canal'),
        ),
    ]
