# Generated by Django 5.1.15 on 2026-03-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0021_telegram_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_access_token',
            field=models.CharField(blank=True, default='', help_text='Token permanente de la Meta Business App para WhatsApp Cloud API.', max_length=500, verbose_name='WhatsApp Access Token'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, default='', help_text='ID del número en Meta Developer Console (no el número real).', max_length=100, verbose_name='WhatsApp Phone Number ID'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='whatsapp_to_number',
            field=models.CharField(blank=True, default='', help_text='Formato 51XXXXXXXXX. Separar por coma para múltiples destinatarios.', max_length=500, verbose_name='Número(s) Destino WhatsApp'),
        ),
    ]
