# Generated by Django 5.1.15 on 2026-05-21 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_empresa_plan_cuentas'),
        ('personal', '0033_personal_personal_empresa_estado_idx_and_more'),
        ('tareo', '0037_afp_tasas_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='afp_tasas_vigencia',
            field=models.CharField(blank=True, help_text="Cuatrimestre de vigencia (ej. 'Q2-2026' o '2026-04 a 2026-07').", max_length=20, verbose_name='Vigencia tasas AFP'),
        ),
        migrations.CreateModel(
            name='BriefingServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, verbose_name='Fecha del servicio')),
                ('servicio', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('CENA', 'Cena'), ('CONTINUO', 'Servicio continuo'), ('EVENTO', 'Evento especial')], default='ALMUERZO', max_length=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=10)),
                ('covers_esperados', models.IntegerField(default=0, help_text='Reservaciones confirmadas + walk-ins estimados.', verbose_name='Covers esperados')),
                ('notas_chef', models.TextField(blank=True, help_text='Mensaje del chef ejecutivo a la brigada.', verbose_name='Notas del Chef')),
                ('especiales', models.TextField(blank=True, help_text='Sugerencias del día / off-menu. Uno por línea.', verbose_name='Platos especiales del día')),
                ('items_86', models.TextField(blank=True, help_text='Platos NO disponibles. Crítico comunicar al salón.', verbose_name="Items 86'd (sin stock)")),
                ('vips_alergias', models.TextField(blank=True, help_text='Mesas con atención especial. Ej: Mesa 4: alergia gluten severa.', verbose_name='VIPs / Alergias / Cumpleaños')),
                ('dress_code', models.CharField(blank=True, help_text='Uniforme del día. Ej: Protocolo formal, evento blanco, etc.', max_length=100, verbose_name='Dress code')),
                ('notas_operativas', models.TextField(blank=True, help_text='Otros: corte de servicio, prueba de menú, visita inspección, etc.', verbose_name='Notas operativas')),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(help_text='Local / RUC al que corresponde el briefing.', on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='empresas.empresa')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefings_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Briefing del Día',
                'verbose_name_plural': 'Briefings del Día',
                'ordering': ['-fecha', 'servicio'],
            },
        ),
        migrations.CreateModel(
            name='BriefingLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings_leidos', to='personal.personal')),
                ('briefing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='tareo.briefingservicio')),
            ],
            options={
                'verbose_name': 'Lectura de Briefing',
                'verbose_name_plural': 'Lecturas de Briefings',
            },
        ),
        migrations.AddIndex(
            model_name='briefingservicio',
            index=models.Index(fields=['fecha', 'estado'], name='brf_fecha_estado_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='briefingservicio',
            unique_together={('empresa', 'fecha', 'servicio')},
        ),
        migrations.AddIndex(
            model_name='briefinglectura',
            index=models.Index(fields=['briefing', 'leido_en'], name='brfl_brf_fecha_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='briefinglectura',
            unique_together={('briefing', 'personal')},
        ),
    ]
