# Generated by Django 5.1.15 on 2026-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0038_alter_configuracionsistema_afp_tasas_vigencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimenturno',
            name='dia_descanso',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=6, help_text='Domingo por defecto. Solo aplica a regímenes semanales con descanso fijo (gastronomía 6×1, oficina 5×2). En regímenes acumulativos/rotativos no se usa.', verbose_name='Día de Descanso Semanal'),
        ),
    ]
