# Generated by Django 5.1.15 on 2026-06-11 15:34

import core.crypto_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0039_dia_descanso_semanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_api_key',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Clave API de Gemini, DeepSeek u OpenAI. No aplica para Ollama.', max_length=500, verbose_name='API Key del proveedor'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='ia_gemini_api_key',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Clave API de Gemini exclusiva para OCR de PDFs escaneados. Permite usar DeepSeek para chat y Gemini para OCR simultáneamente. Si está vacía y el proveedor principal es Gemini, se usa ia_api_key.', max_length=500, verbose_name='API Key Gemini (OCR)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='openclaw_gateway_token',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Token de autenticación para OpenClaw (si aplica).', max_length=200, verbose_name='OpenClaw Gateway Token'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='telegram_bot_token',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Token del bot de Telegram (obtenido desde @BotFather).', max_length=200, verbose_name='Token del Bot de Telegram'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='whatsapp_access_token',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Token permanente de la Meta Business App para WhatsApp Cloud API.', max_length=500, verbose_name='WhatsApp Access Token'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='zapsign_api_key',
            field=core.crypto_fields.EncryptedCharField(blank=True, help_text='Token API de ZapSign para firma digital. Obtener en app.zapsign.com.br/settings/tokens', max_length=200, verbose_name='ZapSign API Key'),
        ),
    ]
