# Generated by Django 5.1.15 on 2026-06-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0041_encrypt_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='telegram_chat_aprobaciones',
            field=models.CharField(blank=True, default='', help_text='Chat ID del admin que recibe solicitudes con botones Aprobar/Rechazar (vacaciones, préstamos/adelantos). Distinto del canal de vacantes. Obtén el tuyo con @userinfobot.', max_length=100, verbose_name='Chat ID para aprobaciones'),
        ),
    ]
