# Generated by Django 5.1.15 on 2026-06-29 23:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0042_configuracionsistema_telegram_chat_aprobaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='sctr_activo',
            field=models.BooleanField(default=True, help_text="Si está activo, calcula SCTR Salud y Pensión a los trabajadores marcados como 'Afecto SCTR' (actividad de riesgo). No afecta al resto.", verbose_name='SCTR activo'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='sctr_pension_tasa',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.30'), help_text='% sobre remuneración computable, aporte empleador (invalidez/sepelio). Referencial; ajustar a la prima real de tu póliza.', max_digits=6, verbose_name='Tasa SCTR Pensión (%)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='sctr_salud_tasa',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.55'), help_text='% sobre remuneración computable, aporte empleador. Referencial; ajustar a la prima real de tu póliza (Anexo 5 DS 009-97-SA).', max_digits=6, verbose_name='Tasa SCTR Salud (%)'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vida_ley_activo',
            field=models.BooleanField(default=True, help_text='Si está activo, calcula la prima de Vida Ley (D.Leg. 688) para todos los trabajadores como costo del empleador.', verbose_name='Seguro Vida Ley activo'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='vida_ley_tasa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.53'), help_text='% sobre remuneración mensual, prima a cargo del empleador. Referencial (~0.53%); ajustar a la prima real de tu póliza.', max_digits=6, verbose_name='Tasa Vida Ley (%)'),
        ),
    ]
