# Generated by Django 5.1.15 on 2026-06-30 03:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0043_configuracionsistema_sctr_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsistema',
            name='sctr_pension_tasa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.73'), help_text='% sobre remuneración computable, aporte empleador (invalidez/sepelio). Referencial; ajustar a la prima real de tu póliza.', max_digits=6, verbose_name='Tasa SCTR Pensión (%)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='sctr_salud_tasa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.80'), help_text='% sobre remuneración computable, aporte empleador. SCTR no tiene tasa fija: se negocia por nivel de riesgo. Referencia combinada (salud+pensión) por nivel: I 0.63% · II 1.23% · III 1.53% · IV 1.83%. Ajustar a la prima real de tu póliza (Anexo 5 DS 009-97-SA).', max_digits=6, verbose_name='Tasa SCTR Salud (%)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='vida_ley_tasa',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.71'), help_text='% sobre remuneración mensual, prima a cargo del empleador. Vida Ley no tiene tasa fija (es prima de seguro); referencial de mercado ~0.71%. Ajustar a la prima real de tu póliza (tope RMA).', max_digits=6, verbose_name='Tasa Vida Ley (%)'),
        ),
    ]
