# Generated by Django 5.1.15 on 2026-07-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareo', '0044_alter_configuracionsistema_sctr_pension_tasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='rubro',
            field=models.CharField(choices=[('GENERAL', 'General / Oficina'), ('GASTRONOMIA', 'Gastronomía'), ('CONSTRUCCION', 'Construcción Civil'), ('MINERIA', 'Minería'), ('AUDIOVISUAL', 'Audiovisual / Agencia')], default='GENERAL', help_text='Preconfigura módulos según el giro (ej. construcción/minería encienden el Roster Matricial por jornada atípica).', max_length=20, verbose_name='Rubro / Industria'),
        ),
    ]
