# Generated by Django 5.1.15 on 2026-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0006_campanacomunicacion'),
        ('personal', '0034_add_roster_gastro'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificacion',
            name='notif_dest_estado_idx',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='archivada_en',
            field=models.DateTimeField(blank=True, help_text='Si está seteado, va al tab Archivadas y se excluye del inbox principal.', null=True, verbose_name='Archivada en'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, help_text='Si está en el futuro, la notificación se oculta del inbox principal hasta esa fecha (tab Snoozed la muestra).', null=True, verbose_name='Snoozed hasta'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='plantillanotificacion',
            name='tipo',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App'), ('WHATSAPP', 'WhatsApp'), ('AMBOS', 'Ambos')], default='IN_APP', max_length=10, verbose_name='Canal de envío'),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='notif_nominas',
            field=models.BooleanField(default=True, verbose_name='Nóminas / Boletas'),
        ),
        migrations.AlterField(
            model_name='preferencianotificacion',
            name='sonido_habilitado',
            field=models.BooleanField(default=True, verbose_name='Sonido de notificación'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario', 'archivada_en'], name='comunicacio_destina_c3149f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['destinatario', 'snoozed_until'], name='comunicacio_destina_3f1e6a_idx'),
        ),
    ]
