# Generated by Django 5.1.15 on 2026-06-11 15:34

import core.crypto_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0007_add_notif_snooze_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsmtp',
            name='smtp_password',
            field=core.crypto_fields.EncryptedCharField(blank=True, max_length=200, verbose_name='Contraseña SMTP'),
        ),
    ]
