# Generated by Django 5.1.15 on 2026-05-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(db_index=True, help_text='Número en formato internacional sin +, ej. 51987654321', max_length=20, unique=True)),
                ('nombre_wa', models.CharField(blank=True, default='', help_text='pushName visible en WhatsApp', max_length=120)),
                ('estado', models.CharField(choices=[('BOT', 'Bot atendiendo'), ('HANDOFF', 'Asignado a humano'), ('CERRADO', 'Cerrado')], db_index=True, default='BOT', max_length=10)),
                ('menu_state', models.CharField(choices=[('INICIO', 'Menú inicio'), ('ESPERA_DEMO_NOMBRE', 'Esperando nombre (flujo demo)'), ('ESPERA_DEMO_EMPRESA', 'Esperando empresa (flujo demo)'), ('ESPERA_DEMO_EMPLEADOS', 'Esperando #empleados (flujo demo)')], default='INICIO', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_index=True)),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('no_leidos', models.PositiveIntegerField(default=0)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación WhatsApp',
                'verbose_name_plural': 'Conversaciones WhatsApp',
                'ordering': ['-ultimo_mensaje_at'],
            },
        ),
        migrations.CreateModel(
            name='WaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('empresa', models.CharField(blank=True, default='', max_length=180)),
                ('num_empleados', models.CharField(blank=True, default='', help_text='Texto libre porque el cliente puede escribir "más de 100"', max_length=40)),
                ('telefono', models.CharField(db_index=True, max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('origen', models.CharField(choices=[('BOT_DEMO', 'Bot — flujo demo'), ('MANUAL', 'Capturado manualmente')], default='BOT_DEMO', max_length=20)),
                ('contactado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='wa_marketing.waconversacion')),
            ],
            options={
                'verbose_name': 'Lead WhatsApp',
                'verbose_name_plural': 'Leads WhatsApp',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='WaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('IN', 'Entrante'), ('OUT', 'Saliente')], db_index=True, max_length=3)),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('MENU', 'Menú/lista'), ('SISTEMA', 'Sistema (interno)')], default='TEXTO', max_length=10)),
                ('cuerpo', models.TextField()),
                ('wa_message_id', models.CharField(blank=True, default='', help_text='ID externo del mensaje (Baileys/Meta)', max_length=120)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='wa_marketing.waconversacion')),
                ('enviado_por', models.ForeignKey(blank=True, help_text='User que envió manualmente (handoff). Null si fue el bot.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['conversacion', 'creado_en'], name='wa_marketin_convers_3b5145_idx')],
            },
        ),
    ]
