# Generated by Django 5.1.15 on 2026-05-29 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacapacitacion',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='capacitaciones/certificados/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])], verbose_name='Certificado'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='material_archivo',
            field=models.FileField(blank=True, null=True, upload_to='capacitaciones/material/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'jpg', 'png'])], verbose_name='Material (archivo)'),
        ),
    ]
