# Generated by Django 5.1.15 on 2026-05-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='cv_idiomas',
            field=models.JSONField(blank=True, default=list, verbose_name='Idiomas detectados'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='cv_parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de parseo'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='cv_score',
            field=models.IntegerField(default=0, help_text='Puntaje 0-100 de match con la vacante (calculado).', verbose_name='Score de matching'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='cv_skills',
            field=models.JSONField(blank=True, default=list, help_text='Lista de skills (JSON array) detectados en el CV.', verbose_name='Skills detectados'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='cv_texto_extraido',
            field=models.TextField(blank=True, default='', help_text='Texto plano extraído del PDF/DOCX vía pipeline NexoTalent (PyMuPDF/pdfplumber/python-docx).', verbose_name='Texto extraído del CV'),
        ),
    ]
