# Generated by Django 5.1.15 on 2026-05-25 02:46
# Audit perf 2026-05-24: índice compuesto (estado, etapa) en Postulacion
# para acelerar pipeline_panel (filtra estado='ACTIVA' como entry point).
# Sin este índice, PG hace seq scan con >5K candidatos históricos.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0003_postulacion_tags'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postulacion',
            index=models.Index(fields=['estado', 'etapa'], name='postulacion_estado_etapa_idx'),
        ),
    ]
