# Generated by Django 5.1.15 on 2026-05-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0004_add_postulacion_estado_etapa_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='fuente',
            field=models.CharField(choices=[('PORTAL', 'Portal de Empleo'), ('LINKEDIN', 'LinkedIn'), ('REFERIDO', 'Referido'), ('HEADHUNTER', 'Headhunter'), ('BANCO', 'Banco de Talento'), ('OTRO', 'Otro')], default='PORTAL', max_length=12, verbose_name='Fuente'),
        ),
    ]
