# Generated by Django 5.1.15 on 2026-07-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclutamiento', '0006_vacante_aprobacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('POR_APROBAR', 'Por aprobar'), ('APROBADA', 'Aprobada'), ('PUBLICADA', 'Publicada'), ('EN_PROCESO', 'En Proceso'), ('CUBIERTA', 'Cubierta'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
    ]
