# Generated by Django 5.1.15 on 2026-03-05 02:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0019_add_eps_viaticos_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='alimentacion_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Asignación mensual de alimentación. No remunerativa (D.Leg. 728 Art. 19°). Se incluye en el flujo de caja de planilla.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Alimentación mensual'),
        ),
        migrations.AddField(
            model_name='personal',
            name='cond_trabajo_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Asignación mensual no remunerativa por condiciones de trabajo (hospedaje en proyecto/obra). No forma parte de la base remunerativa ni de IR 5ta. Se incluye en el flujo de caja de planilla.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Condición de Trabajo / Hospedaje (mensual)'),
        ),
    ]
