# Generated by Django 5.1.15 on 2026-05-20 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_knowledge_article_pgvector'),
        ('empresas', '0008_cargo_model_plantilla_evolution'),
        ('personal', '0032_merge_0029_activoasignado_0031_merge_20260413_2247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['empresa', 'estado'], name='personal_empresa_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='personal',
            index=models.Index(fields=['empresa', 'grupo_tareo', 'estado'], name='personal_emp_grupo_est_idx'),
        ),
    ]
