# Generated by Django 5.1.15 on 2026-05-22 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0033_personal_personal_empresa_estado_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoGastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('hora_entrada', models.TimeField(verbose_name='Hora entrada')),
                ('hora_salida', models.TimeField(verbose_name='Hora salida')),
                ('color', models.CharField(default='#0f766e', help_text='HEX color para badge en el grid (ej: #0f766e)', max_length=7, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Turno Gastronomia',
                'verbose_name_plural': 'Turnos Gastronomia',
                'ordering': ['hora_entrada', 'codigo'],
                'indexes': [models.Index(fields=['activo'], name='personal_tu_activo_cc23ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionRosterQuincena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_roster_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_roster', to='personal.personal', verbose_name='Personal')),
                ('turno', models.ForeignKey(blank=True, help_text='Null = dia libre', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='personal.turnogastronomia', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Asignacion Roster Quincena',
                'verbose_name_plural': 'Asignaciones Roster Quincena',
                'ordering': ['fecha', 'personal'],
                'indexes': [models.Index(fields=['fecha'], name='personal_as_fecha_15e049_idx'), models.Index(fields=['personal', 'fecha'], name='personal_as_persona_a563d8_idx')],
                'unique_together': {('personal', 'fecha')},
            },
        ),
    ]
