# Generated by Django 5.1.15 on 2026-05-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0030_activoasignado'),
        ('personal', '0034_add_roster_gastro'),
    ]

    operations = [
    ]
