# Generated by Django 5.1.15 on 2026-05-25 01:57
# Reconcilia leaf nodes en producción tras aplicar 0035_merge.
# Dependencies corregidas: apunta a las versiones canónicas del repo.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0030_activoasignado'),
        ('personal', '0035_merge_0029_activoasignado_0034_add_roster_gastro'),
    ]

    operations = [
    ]
