# Generated by Django 5.1.15 on 2026-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0036_merge_20260524_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='dia_descanso_semanal',
            field=models.CharField(blank=True, choices=[('', 'Domingo (por defecto)'), ('0', 'Lunes'), ('1', 'Martes'), ('2', 'Miércoles'), ('3', 'Jueves'), ('4', 'Viernes'), ('5', 'Sábado'), ('6', 'Domingo')], default='', help_text='Solo aplica a regímenes con descanso fijo (gastronomía 6×1, oficina 5×2). En blanco = domingo. Para roster acumulativo 21×7/14×7 este campo no se usa.', max_length=2, verbose_name='Día de Descanso Semanal'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='grupo_tareo',
            field=models.CharField(choices=[('STAFF', 'Staff (HE compensatorias — banco de horas)'), ('RCO', 'Operativo (HE pagadas 25/35/100%)'), ('OTRO', 'Otro / No aplica')], default='STAFF', help_text='Determina cómo se tratan las HE: banco (Staff) o pago (Operativo)', max_length=10, verbose_name='Grupo Tareo'),
        ),
    ]
