# Generated by Django 5.1.15 on 2026-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0037_dia_descanso_semanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='billetera_acuerdo',
            field=models.BooleanField(default=False, help_text='El pago por billetera requiere acuerdo previo del trabajador; el empleador no puede imponerlo.', verbose_name='Acuerdo del trabajador (Ley 32413)'),
        ),
        migrations.AddField(
            model_name='personal',
            name='billetera_celular',
            field=models.CharField(blank=True, help_text='9 dígitos, empieza en 9', max_length=9, verbose_name='Celular de la billetera'),
        ),
        migrations.AddField(
            model_name='personal',
            name='billetera_tipo',
            field=models.CharField(blank=True, choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('LIGO', 'Ligo'), ('KONTIGO', 'Kontigo'), ('OTRA', 'Otra billetera')], max_length=10, verbose_name='Billetera digital'),
        ),
        migrations.AddField(
            model_name='personal',
            name='medio_pago_haberes',
            field=models.CharField(choices=[('CUENTA', 'Cuenta bancaria'), ('BILLETERA', 'Billetera digital')], default='CUENTA', max_length=10, verbose_name='Medio de pago de haberes'),
        ),
    ]
