# Generated by Django 5.1.15 on 2026-06-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0038_personal_billetera_acuerdo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='afecto_sctr',
            field=models.BooleanField(default=False, help_text='Marca a los trabajadores en actividades de alto riesgo (construcción, minería, etc., Anexo 5 DS 009-97-SA). El empleador aporta SCTR Salud y Pensión solo por ellos. El personal administrativo NO debe marcarse.', verbose_name='Afecto SCTR (actividad de riesgo)'),
        ),
    ]
