# Generated by Django 5.1.15 on 2026-07-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0039_personal_afecto_sctr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='regimen_laboral',
            field=models.CharField(blank=True, choices=[('GENERAL', 'Régimen General (D.Leg. 728)'), ('MICROEMPRESA', 'Microempresa (REMYPE)'), ('PEQUEÑA', 'Pequeña Empresa (REMYPE)'), ('AGRARIO', 'Agrario (Ley 31110)'), ('CONSTRUCCION', 'Construcción Civil (CAPECO-FTCCP)'), ('MINERIA', 'Minería (D.S. 030-89-TR)')], default='GENERAL', help_text='Determina la estrategia de cálculo de planilla (CONSTRUCCION y MINERIA tienen reglas propias).', max_length=50, verbose_name='Régimen Laboral'),
        ),
    ]
