# Generated by Django 5.1.15 on 2026-07-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0040_alter_personal_regimen_laboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='categoria_construccion',
            field=models.CharField(blank=True, choices=[('OPERARIO', 'Operario'), ('OFICIAL', 'Oficial'), ('PEON', 'Peón')], help_text='Operario / Oficial / Peón. Solo aplica al régimen de construcción civil; fija el jornal básico (tabla CAPECO).', max_length=10, verbose_name='Categoría Construcción Civil'),
        ),
    ]
