# Generated by Django 5.1.15 on 2026-07-03 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_checklistgastronomia'),
        ('personal', '0041_personal_categoria_construccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_creado', models.BooleanField(default=False, verbose_name='Correo corporativo creado')),
                ('correo_corporativo', models.EmailField(blank=True, max_length=254, verbose_name='Correo corporativo')),
                ('usuario_ad_creado', models.BooleanField(default=False, verbose_name='Usuario AD/SSO creado')),
                ('usuario_ad', models.CharField(blank=True, max_length=100, verbose_name='Usuario AD/SSO')),
                ('equipo_entregado', models.BooleanField(default=False, verbose_name='Equipo entregado')),
                ('accesos_sistemas', models.TextField(blank=True, help_text='Sistemas, carpetas o licencias habilitados', verbose_name='Accesos a sistemas')),
                ('fotocheck_entregado', models.BooleanField(default=False, verbose_name='Fotocheck entregado')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_ti_actualizados', to=settings.AUTH_USER_MODEL)),
                ('equipo_asignado', models.ForeignKey(blank=True, help_text='Activo entregado al ingresar (laptop, celular, EPP...)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_ti', to='personal.activoasignado', verbose_name='Equipo asignado')),
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_ti', to='onboarding.procesoonboarding', verbose_name='Proceso de Onboarding')),
            ],
            options={
                'verbose_name': 'Checklist TI',
                'verbose_name_plural': 'Checklists TI',
            },
        ),
    ]
