# Generated by Django 5.1.15 on 2026-05-29 05:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='descuentoplanilla',
            new_name='descuentos__persona_c00ddd_idx',
            old_name='desc_personal_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='descuentoplanilla',
            new_name='descuentos__estado_1beaaa_idx',
            old_name='desc_estado_inicio_idx',
        ),
        migrations.AlterField(
            model_name='aplicaciondescuento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='cuota_mensual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se calcula automáticamente si se deja vacío.', max_digits=10, null=True, verbose_name='Cuota Mensual (S/)'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='detalle',
            field=models.TextField(help_text='Describe el motivo específico del descuento.', verbose_name='Detalle / Descripción'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='documento_soporte',
            field=models.FileField(blank=True, help_text='Foto del daño, acta firmada, orden judicial, etc.', null=True, upload_to='descuentos/%Y/%m/', verbose_name='Documento de Soporte'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='fecha_inicio_descuento',
            field=models.DateField(blank=True, help_text='Período de planilla en el que empieza a descontarse.', null=True, verbose_name='Inicio del Descuento'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='num_cuotas',
            field=models.PositiveSmallIntegerField(default=1, help_text='En cuántos períodos de planilla se aplicará el descuento.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)], verbose_name='N° de Cuotas'),
        ),
        migrations.AlterField(
            model_name='descuentoplanilla',
            name='requiere_consentimiento',
            field=models.BooleanField(default=True, help_text='Embargos y pensiones judiciales no lo requieren.', verbose_name='Requiere Consentimiento Escrito'),
        ),
    ]
