# Generated by Django 5.1.15 on 2026-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_cargo_model_plantilla_evolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plan_cuentas',
            field=models.JSONField(blank=True, help_text='JSON con cuentas contables personalizadas para esta empresa. Llaves esperadas: sueldos_debe, gratif_debe, essalud_debe, rem_pagar_haber, afp_pagar_haber, onp_pagar_haber, essalud_pagar_haber. Cada valor es [codigo, nombre].', null=True, verbose_name='Plan de cuentas (override)'),
        ),
    ]
