# Generated by Django 5.1.15 on 2026-06-11 15:34

import core.crypto_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_historialpago_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='email_host_password',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Contraseña o App Password', max_length=200, verbose_name='Contraseña SMTP'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='openclaw_gateway_token',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Token de autenticacion para OpenClaw (si aplica)', max_length=200, verbose_name='OpenClaw Gateway Token'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='whatsapp_access_token',
            field=core.crypto_fields.EncryptedCharField(blank=True, default='', help_text='Token permanente de la Meta Business App (solo para Meta Cloud API)', max_length=500, verbose_name='WhatsApp Access Token'),
        ),
    ]
