# Generated by Django 5.1.15 on 2026-06-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_encrypt_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpago',
            name='metodo_pago',
            field=models.CharField(choices=[('YAPE', 'Yape'), ('PLIN', 'Plin'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('TARJETA', 'Tarjeta de crédito/débito'), ('MERCADOPAGO', 'MercadoPago (online)'), ('EFECTIVO', 'Efectivo'), ('OTRO', 'Otro')], default='YAPE', max_length=15),
        ),
    ]
