# Generated by Django 5.1.15 on 2026-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_alter_historialpago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(choices=[('GENERAL', 'General / Oficina'), ('GASTRONOMIA', 'Gastronomía'), ('CONSTRUCCION', 'Construcción Civil'), ('MINERIA', 'Minería'), ('AUDIOVISUAL', 'Audiovisual / Agencia')], default='GENERAL', help_text='Giro operativo de la empresa (construcción, minería, gastronomía…). Distinto del sector legal (CIIU).', max_length=20, verbose_name='Rubro / Giro'),
        ),
    ]
