# Generated by Django 5.1.15 on 2026-05-22 06:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_empresa_plan_cuentas'),
        ('encuestas', '0001_initial'),
        ('personal', '0033_personal_personal_empresa_estado_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PulseSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField(help_text='Número ISO de semana (1-53)')),
                ('anio', models.PositiveIntegerField()),
                ('animo', models.PositiveSmallIntegerField(choices=[(1, '😡 Muy mal'), (2, '😟 Mal'), (3, '😐 Regular'), (4, '🙂 Bien'), (5, '😄 Excelente')], help_text='¿Cómo te sentiste esta semana?')),
                ('que_falta', models.TextField(blank=True, help_text='¿Qué falta para mejorar?')),
                ('propuestas', models.TextField(blank=True, help_text='Una propuesta concreta')),
                ('nps', models.IntegerField(blank=True, help_text='¿Recomendarías trabajar aquí? (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pulses_semanales', to='empresas.empresa')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulses_semanales', to='personal.personal')),
            ],
            options={
                'verbose_name': 'Pulse Semanal',
                'verbose_name_plural': 'Pulses Semanales',
                'ordering': ['-anio', '-semana'],
                'indexes': [models.Index(fields=['empresa', 'anio', 'semana'], name='encuestas_p_empresa_1d8ad9_idx'), models.Index(fields=['anio', 'semana'], name='encuestas_p_anio_630d4d_idx')],
                'unique_together': {('personal', 'semana', 'anio')},
            },
        ),
    ]
